name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL = "DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMDI5OGM3ZWYtNjU5OS00MDI4LTkwNmItOGQ1MTJmNDJlZWVjIiwidGVuYW50X2lkIjoiNGFhYjM2N2MzNmMzZDIwNTYyOWZmMmYyOWNjMWMzM2E5NjM5MjcwMGQzYThkMzY1NjQxNmNhYjlmYWQ4NDYyZCIsImludGVybmFsX3NlY3JldCI6IjNhMzkxMjFkLWY2MGItNDY1NS1hZWU0LTdhMzQwMjQ3MGZjNyJ9.yHx2E7Uf5AuY_uRkwu-d_YwZOuHCGDJLK1CGOyoZJck""
